export const abi = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "OWNER",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "VALUE",
        type: "uint256",
      },
    ],
    name: "DEPOSIT",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "VALUE",
        type: "uint256",
      },
    ],
    name: "TARGET_REACHED",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "OWNER",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "VALUE",
        type: "uint256",
      },
    ],
    name: "WITHDRAW",
    type: "event",
  },
  {
    inputs: [],
    name: "AutoSwapEnabled",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "ClaimMyTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "ProjectID", type: "uint64" },
      { internalType: "uint256", name: "USDvalue", type: "uint256" },
    ],
    name: "DepositUSD",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "DisplayFromID",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "ProjectID", type: "uint64" },
      { internalType: "uint64", name: "startPos", type: "uint64" },
      { internalType: "uint64", name: "endPos", type: "uint64" },
    ],
    name: "DistributeTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "ProjectID", type: "uint64" },
      { internalType: "address", name: "PayoutContractAddr", type: "address" },
    ],
    name: "FundTokensBalanceToProject",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "MainWallet",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "ContractAddress", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "RecoverTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "SendDepositsToBankWallet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "StartClaiming",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "ProjectName", type: "string" },
      { internalType: "string", name: "LogoURL", type: "string" },
      {
        internalType: "uint256",
        name: "minimumInvestmentUSD",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maximumInvestmentUSD",
        type: "uint256",
      },
      { internalType: "uint256", name: "InvestmentGoalUSD", type: "uint256" },
      { internalType: "address", name: "PayoutTokenAddr", type: "address" },
      { internalType: "address", name: "BankWalletAddr", type: "address" },
      { internalType: "uint256", name: "DelaybeforeStart_h", type: "uint256" },
      { internalType: "uint256", name: "Duration_h", type: "uint256" },
    ],
    name: "StartNewProject",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "USDContract",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "WorkHelperWallet",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint64", name: "", type: "uint64" },
    ],
    name: "_balanceUSD",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "", type: "uint64" },
      { internalType: "uint64", name: "", type: "uint64" },
    ],
    name: "_investorID",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint64", name: "", type: "uint64" },
    ],
    name: "_tokensReceived",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "countActiveProjects",
    outputs: [{ internalType: "uint64", name: "count", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "disableAutoSwap",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "disableDeposits",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "enableAutoSwap",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "enableDeposits",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getActiveProjects",
    outputs: [
      { internalType: "uint64", name: "pos", type: "uint64" },
      { internalType: "uint64[]", name: "", type: "uint64[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getClaimStatus",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getCountDown",
    outputs: [
      { internalType: "uint256", name: "Days", type: "uint256" },
      { internalType: "uint256", name: "Hours", type: "uint256" },
      { internalType: "uint256", name: "Minutes", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "ProjectID", type: "uint64" },
      { internalType: "address", name: "holder", type: "address" },
    ],
    name: "getDepositedUSD",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getETHBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getInvestStatus",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getInvestmentGoal",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "ProjectID", type: "uint64" },
      { internalType: "uint64", name: "Num", type: "uint64" },
    ],
    name: "getInvestorID",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getMaxInvestment",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getMinInvestment",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getMyTokensClaimed",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getMyUSDInvested",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getPayoutDecimals",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getPayoutName",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getPayoutSymbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getPayoutTokenBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getPercInvested",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getProjectDetails",
    outputs: [
      { internalType: "string", name: "Logo", type: "string" },
      { internalType: "string", name: "Name", type: "string" },
      { internalType: "string", name: "Status", type: "string" },
      { internalType: "uint256", name: "USDInvested", type: "uint256" },
      { internalType: "uint256", name: "PercInvested", type: "uint256" },
      { internalType: "uint256", name: "Goal", type: "uint256" },
      { internalType: "uint256", name: "TokensPaidOut", type: "uint256" },
      { internalType: "uint8", name: "PayoutDecimals", type: "uint8" },
      { internalType: "uint256", name: "totalTokens", type: "uint256" },
      { internalType: "uint256", name: "MinInvest", type: "uint256" },
      { internalType: "uint256", name: "MaxInvest", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getProjectLogo",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getProjectName",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getProjectStatus",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amountBNB", type: "uint256" }],
    name: "getTokenprice",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getTokensPaidOut",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getTotalTokens",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getUSDBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "ProjectID", type: "uint64" }],
    name: "getUSDInvested",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getUSDcontractAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "ProjectID", type: "uint64" },
      { internalType: "address", name: "holder", type: "address" },
    ],
    name: "getclaimableTokens",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getmaxGoalExceedance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "ProjectID", type: "uint64" },
      { internalType: "address", name: "holder", type: "address" },
    ],
    name: "gettokensReceived",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "startPos", type: "uint64" }],
    name: "setDisplayFromID",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "addr", type: "address" }],
    name: "setHelperWallet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "ProjectID", type: "uint64" },
      { internalType: "uint256", name: "USDvalue", type: "uint256" },
    ],
    name: "setInvestmentGoal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "addr", type: "address" }],
    name: "setMainWallet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "ProjectID", type: "uint64" },
      { internalType: "uint256", name: "USDvalue", type: "uint256" },
    ],
    name: "setMaxInvestment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "ProjectID", type: "uint64" },
      { internalType: "uint256", name: "USDvalue", type: "uint256" },
    ],
    name: "setMinInvestment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "ProjectID", type: "uint64" },
      { internalType: "address", name: "addr", type: "address" },
    ],
    name: "setPayoutContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "ProjectID", type: "uint64" },
      { internalType: "bool", name: "isVisible", type: "bool" },
    ],
    name: "setProjectVisibility",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "addr", type: "address" }],
    name: "setUSDContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "dec", type: "uint256" }],
    name: "setUSDdecimals",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bool", name: "enabled", type: "bool" }],
    name: "setdistributeAtEthDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bool", name: "enabled", type: "bool" }],
    name: "setdistributeAtUSDDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "USDvalue", type: "uint256" }],
    name: "setmaxGoalExceedance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "ProjectID", type: "uint64" },
      { internalType: "address", name: "PayoutContractAddr", type: "address" },
    ],
    name: "setpayoutToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
];
